POST  http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
  "username": "s123456@studenti.polito.it",
  "password": "password"
}

###
GET http://localhost:3001/api/studyplans/302223 HTTP/1.1

###
DELETE http://localhost:3001/api/studyplan/123456/02LSEOV HTTP/1.1

###
PUT http://localhost:3001/api/studyplans/789123/full HTTP/1.1

